---
- name: Prepare the virthost for PXE forwarding
  hosts: virthost
  gather_facts: no
  roles:
    - ansible-role-tripleo-baremetal-prep-virthost

- include: provision.yml

- name: Add macvtap devices to PXE bot from virt undercloud
  hosts: virthost
  gather_facts: no
  roles:
    - ansible-role-tripleo-baremetal-virt-undercloud

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/teardown
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  roles:
    - rebuild-inventory

- name:  Install the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud

- name:  Post undercloud install steps
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-undercloud-post

- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-overcloud

- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-inventory

- name:  validate the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - ansible-role-tripleo-overcloud-validate
